name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run flake8
        run: |
          echo "Running flake8..."
          flake8 app/ --max-line-length=100 --ignore=E402,W503 || echo "Flake8 found issues"
        continue-on-error: true
      
      - name: Check formatting with black
        run: black --check app/
        continue-on-error: true
      
      - name: Type checking with mypy
        run: mypy app/ --ignore-missing-imports
        continue-on-error: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium --with-deps
      
      - name: Debug Python version and packages
        run: |
          python --version
          pip list | grep -E "(pytest|flake8|black|mypy)"
      
      - name: Run pytest
        run: pytest --cov=app --cov-report=xml
        continue-on-error: true
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        continue-on-error: true

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t passmark-scraper .
      
      - name: Test Docker container
        run: |
          docker run -d --name test-container -p 9091:9091 passmark-scraper
          sleep 15
          wget -q --spider http://localhost:9091/health || exit 1
          docker stop test-container
          docker rm test-container

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true
      
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

